Areas/User/Controllers/ContactSkillController.cs
using Contacts_API.Data;
using Contacts_API.Models;
using Contacts_API.ViewModel;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.VisualBasic;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
#pragma warning disable 1587
//////////////////////////////////////////
/// ContactSkillController              //
/// This controler  manage the link     //    
/// between the table Contact and skill //
///                                     //           
/// Create by Legland Ludovic           //
/// Creation date: 06.07.2020           //
//////////////////////////////////////////
#pragma warning restore 1587
namespace Contacts_API.Areas.User.Controllers
{
    [Area("User")]
    public class ContactSkillController : Controller
    {
        private readonly ApplicationDbContext _db;

        /// <summary>
        /// Set the db context
        /// </summary>
        /// <param name="db"></param>
        public ContactSkillController(ApplicationDbContext db)
        {
            _db = db;
        }

        /// <summary>
        /// initialize the View withe the ViewModel SkillAndContactViewModel with the db context of the 3 tables Contact, skill and contactSkill
        /// Initialize each skills and contacts who are link together
        /// </summary>
        /// <returns>View(model)</returns>
        [HttpGet("link")]
        public async Task<IActionResult> Index()
        {
            SkillAndContactViewModel my_model = new SkillAndContactViewModel()
            {
                Contacts = await _db.DbContact.ToListAsync(),
                Skills = await _db.DbSkill.OrderBy(p => p.Ski_name).Distinct().ToListAsync(),
                ContactSkills = await _db.DbContactSkill.ToListAsync(),
                ContactSkill = new ContactSkillModel()
            };

            foreach (ContactSkillModel conSkill in my_model.ContactSkills)
            {
                conSkill.Skill = null;
                conSkill.Contact = null;

                conSkill.Skill = (from s in _db.DbSkill
                                  where s.Id_skill == conSkill.Cs_skillId
                                  orderby s.Ski_name,s.Ski_level
                                  select s).First();
                conSkill.Contact = (from c in _db.DbContact
                                    where c.Id_contact == conSkill.Cs_contactId
                                    orderby c.Con_full_name,c.Con_adress
                                    select c).First();
            }
            return View(my_model);
        }
        /// <summary>
        /// Retrieve every id_skill who are selected in the view and insert the in the table contact skill to create the link 
        /// </summary>
        /// <param name="model"></param>
        /// <returns>redirect to the index View </returns>
        [HttpPost("link/link")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Link(SkillAndContactViewModel model)
        {
            ContactSkillModel skillModel = new ContactSkillModel();

            string selected = Request.Form["chkidSelected"].ToString();
            string[] selectedListId = selected.Split(',');

            foreach (var temp in selectedListId)
            {
                if (selectedListId.Count() > 0 && !string.IsNullOrEmpty(temp))
                {
                    try
                    {
                        skillModel.Cs_contactId = model.ContactSkill.Cs_contactId;
                        skillModel.Cs_skillId = int.Parse(temp);
                        _db.Add(skillModel);
                        await _db.SaveChangesAsync();
                    }
                    catch(Exception)
                    {

                    }

                }
            }
            return RedirectToAction(nameof(Index));
        }

        /// <summary>
        /// Retrive both id skill and contact who are merge in the view 
        /// and split them in order to delete the right line
        /// </summary>
        /// <param name="id"></param>
        /// <returns>redirect to the index View </returns>

        [HttpGet("link/delete")]
        public async Task<IActionResult> Delete(string id)
        {
            string[] selectedListId = id.Split('$');
            int? idContact = int.Parse(selectedListId[0].ToString());
            int? idSkill = int.Parse(selectedListId[1].ToString());

            if (idContact == null || idSkill == null || idContact<1 || idSkill <1)
            {
                return NotFound();
            }
            var contactSkill = await _db.DbContactSkill
                //.Include(c => c.Contact)
                .FirstOrDefaultAsync(m => m.Cs_contactId == idContact && m.Cs_skillId == idSkill);
            if (contactSkill == null)
            {
                return NotFound();
            }

            _db.DbContactSkill.Remove(contactSkill);
            await _db.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ContactSkillModelExists(int id)
        {
            return _db.DbContactSkill.Any(e => e.Cs_contactId == id);
        }
    }
}

Views/Shared/_CreateAndBackToListButton.cshtml
<div class="row">
    <div class="form-group col-md-6">
        <input type="submit" class="btn btn-primary btn-block" value="Submit" />
    </div>
    <div class="form-group col-md-6">
        <a asp-action="Index" class="btn btn-secondary btn-block"><i class="fa fa-table"></i>&ensp; Back to List</a>
    </div>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Contacts_API</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <script src="https://kit.fontawesome.com/3051c09612.js" crossorigin="anonymous"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Contacts_API</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="User" asp-controller="Contact" asp-action="Index">Contact</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="User" asp-controller="Skill" asp-action="Index">Skill</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="User" asp-controller="ContactSkill" asp-action="Index">Link</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Contacts_API - Create by Legland Ludovic</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>